runtime: python310
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  # Remova esta linha: idle_timeout: 5m

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto